### PR TITLE
Feature/upgrade babel to 7

### PR DESCRIPTION
**Pull request by rouvenherzog**
Hello,

we've upgraded out application to use webpack 4.0 and babel 7.
With the upgrade done, `react-ziggeo` does not compile anymore unfortunately. Reason being that  babel 6, with no preset env module specified, adds "strict mode" to all files. This leads to the following error when trying to build the application:

```
ERROR in ./node_modules/react-ziggeo/build/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: ./node_modules/react-ziggeo/build/index.js: 'with' in strict mode (11688:12466)

```

In order to allow projects that run on babel 7 to use the react wrapper, I've upgraded the babel config to compile the code with babel 7 as well. The `.babelrc` and `package.json` changes are generated with [babel upgrade](https://github.com/babel/babel-upgrade).

What do you think?

### CODE REVIEW

**Comment by sambua** [comment]
Hello @rouvenherzog , 

Thanks a lot for taking time and making these changes, will test and merge it.

Thanks a lot for contribution ))

**Comment by Bane-D** [comment]
Hi Rouven,

Following up to let you know that the latest revision of our JS SDK (2.41.2) is `with(obj)` free, and it should be possible to use it within the strict mode.

You will however need to follow these steps: https://github.com/Ziggeo/react-ziggeo#upgrade-ziggeo-sdk to use the `2.41.2` revision of our JS SDK we use by React SDK.

**Comment by diogolessa** [comment]
Hi @Bane-D, I face a similar issue, but with SWC instead of babel. The issue is described here: https://github.com/swc-project/swc/issues/4842

However it seems you suggest us to fork the react-ziggeo, update the dependency version and re-build. I even see one [pull request](https://github.com/Ziggeo/react-ziggeo/pull/99) upgrading it, but it didn't go to the master branch. What prevents you to make this change officially released? I'd really appreciate if we could do so.

Thanks,

**Comment by Bane-D** [comment]
Hi Diogo,

You are right, this is connected issue, still I do feel like there are 2 separate points that should be mentioned here.

**1 - Master branch vs Latest Branch**

Our Master branch is designed to use our "Stable" aka "Default"  branch - of our Ziggeo JS SDK that is utilized by the React and other SDKs.
This has proven to be the best approach for most of our customers as we can then update the default branch as needed and have the update become available without any updates to our customers. I know this might not make sense for everyone, and it is why we also leave all of our versions available for someone to switch to as they prefer manually.

In order to help show how to move to the latest branch and since in React this also includes having some parameters or events included as well one of our teammates made the update to [latest branch](https://github.com/Ziggeo/react-ziggeo/tree/latest-branch) which would make it easier to switch to with any additional React specific updates being present.

**2 - presence of `with`**

This is the actual issue that you and anyone else that uses the `strict` mode likely experience in some way. We have at one point removed the use of the same from our code, however there is still some present in the BetaJS repositories that we are utilizing in the back. This is going to cause some errors or stopping from building the code depending on the setup - and of course only if strict mode is mandatory.

Until the update is made within the BetaJS repositories to address this it is likely going to happen that some error is shown in strict modes, however still the point 1 would be in effect as the React and other SDKs that use the JS SDK utilize the version tagged as "Stable" (quotes used as it is actual name we use, all releases we create go through the testing processes to make sure they are all stable before we release them).

**Comment by diogolessa** [comment]
Hi @Bane-D, thanks for the detailed answer.

Using the latest branch seems a bit off to my use case. Do you have plans to release a new version of stable soon?

**Comment by Bane-D** [comment]
Of course, happy to help Diogo

At the moment our stable tag is pointing to the 2.42.3 and the React SDK seems to be set using the `~2.39.16` while the latest branch seem to be set for `2.41.5`. So in this instance it looks like we could have upgraded both. Will ping some of my colleagues that are more familiar with the React to see about the update.

Once done the React SDK Master branch should be pointing to `~2.42.3` and the latest branch to `~v2.43.3`. We would need to follow up on the exact times related to this.

**Pull request merged**
